services:
  mininet:
    build:
      dockerfile: docker/Dockerfile
    container_name: mininet
    privileged: true
    cap_add:
      - ALL
    ports:
      - "8888:8888"
    volumes:
      - /lib/modules:/lib/modules
      - ./lib-docker:/var/lib/docker
      - ./logs:/logs
      - ./MAppLE:/MAppLE
      - ./docker:/docker
      - ./docker/output:/App/output
    extra_hosts:
      - "quic.clemente.io:10.0.0.20"
